apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml.backup -o vul_app/home/t-u1804/t-u1804.yaml --volumes hostPath
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: cve-2014-0160-nginx
  name: cve-2014-0160-nginx
  namespace: metarget
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
    - name: "8443"
      port: 8443
      targetPort: 443
  selector:
    io.kompose.service: cve-2014-0160-nginx
