apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./xxl-job/unacc/docker-compose.yml.backup
      -o vul_app/xxl-job/unacc/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: xxl-job-unacc-admin
  name: xxl-job-unacc-admin
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: xxl-job-unacc-admin
status:
  loadBalancer: {}
