apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./log4j/CVE-2017-5645/docker-compose.yml -o RCE-FOR-K8S-4/log4j/CVE-2017-5645/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2017-5645-log4j
  name: cve-2017-5645-log4j
  namespace: metarget
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2017-5645-log4j
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./log4j/CVE-2017-5645/docker-compose.yml -o
          RCE-FOR-K8S-4/log4j/CVE-2017-5645/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2017-5645-log4j
    spec:
      containers:
      - image: vulhub/log4j:2.8.1
        imagePullPolicy: IfNotPresent
        name: cve-2017-5645-log4j
        ports:
        - containerPort: 4712
        resources: {}
      restartPolicy: Always
status: {}
