apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./log4j/CVE-2017-5645/docker-compose.yml -o RCE-FOR-K8S-4/log4j/CVE-2017-5645/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2017-5645-log4j
  name: cve-2017-5645-log4j
spec:
  ports:
    - name: "4712"
      port: 4712
      targetPort: 4712
  selector:
    io.kompose.service: cve-2017-5645-log4j
status:
  loadBalancer: {}
