apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./xstream/CVE-2021-29505/docker-compose.yml.backup
      -o vul_app/xstream/CVE-2021-29505/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2021-29505-web
  name: cve-2021-29505-web
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: cve-2021-29505-web
status:
  loadBalancer: {}
