apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./php/8.1-backdoor/docker-compose.yml.backup
      -o vul_app/php/8-1-backdoor/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: php-8-1-backdoor-web
  name: php-8-1-backdoor-web
  namespace: metarget
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: php-8-1-backdoor-web
status:
  loadBalancer: {}
