apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./electron/CVE-2018-15685/docker-compose.yml.backup
      -o vul_app/electron/CVE-2018-15685/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2018-15685-web
  name: cve-2018-15685-web
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: cve-2018-15685-web
status:
  loadBalancer: {}
