apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./kibana/CVE-2019-7609/docker-compose.yml -o RCE-FOR-K8S-4/kibana/CVE-2019-7609/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2018-1297-kibana
  name: cve-2018-1297-kibana
  namespace: metarget
spec:
  ports:
  - name: '5601'
    port: 5601
    targetPort: 5601
  selector:
    io.kompose.service: cve-2018-1297-kibana
status:
  loadBalancer: {}
