apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./kibana/CVE-2019-7609/docker-compose.yml -o RCE-FOR-K8S-4/kibana/CVE-2019-7609/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2018-1297-elasticsearch
  name: cve-2018-1297-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2018-1297-elasticsearch
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./kibana/CVE-2019-7609/docker-compose.yml
          -o RCE-FOR-K8S-4/kibana/CVE-2019-7609/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2018-1297-elasticsearch
    spec:
      containers:
      - image: vulhub/elasticsearch:6.8.6
        imagePullPolicy: IfNotPresent
        name: cve-2018-1297-elasticsearch
        resources: {}
      restartPolicy: Always
status: {}
