apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./apereo-cas/4.1-rce/docker-compose.yml -o RCE-FOR-K8S-4/apereo-cas/4.1-rce/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: apereo-cas-4-1-rce-web
  name: apereo-cas-4-1-rce-web
  namespace: metarget
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apereo-cas-4-1-rce-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./apereo-cas/4.1-rce/docker-compose.yml -o
          RCE-FOR-K8S-4/apereo-cas/4.1-rce/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: apereo-cas-4-1-rce-web
    spec:
      containers:
      - image: vulhub/apereo-cas:4.1.5
        imagePullPolicy: IfNotPresent
        name: apereo-cas-4-1-rce-web
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
