apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./php/CVE-2018-19518/docker-compose.yml -o RCE-FOR-K8S-4/php/CVE-2018-19518/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2018-19518-web
  name: cve-2018-19518-web
  namespace: metarget
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2018-19518-web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./php/CVE-2018-19518/docker-compose.yml -o
          RCE-FOR-K8S-4/php/CVE-2018-19518/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2018-19518-web
    spec:
      containers:
      - image: vulhub/php:5.6-with-imap
        imagePullPolicy: IfNotPresent
        name: cve-2018-19518-web
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: cve-2018-19518-web-hostpath0
      restartPolicy: Always
      volumes:
      - name: cve-2018-19518-web-hostpath0
        hostPath:
          path: php/CVE-2018-19518/www
status: {}
