apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./webmin/CVE-2019-15107/docker-compose.yml -o
      RCE-FOR-K8S-4/webmin/CVE-2019-15107/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2019-15107-web
  name: cve-2019-15107-web
  namespace: metarget
spec:
  ports:
  - name: '10000'
    port: 10000
    targetPort: 10000
  selector:
    io.kompose.service: cve-2019-15107-web
status:
  loadBalancer: {}
