apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./spark/unacc/docker-compose.yml.backup
      -o vul_app/spark/unacc/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-unacc-master
  name: spark-unacc-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-unacc-master
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./spark/unacc/docker-compose.yml.backup
          -o vul_app/spark/unacc/ --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: spark-unacc-master
    spec:
      containers:
      - image: vulhub/spark:2.3.1
        imagePullPolicy: ""
        name: spark-unacc-master
        ports:
        - containerPort: 8080
        - containerPort: 7077
        - containerPort: 6066
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
