apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./spark/unacc/docker-compose.yml.backup
      -o vul_app/spark/unacc/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-unacc-master
  name: spark-unacc-master
  namespace: metarget
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "7077"
    port: 7077
    targetPort: 7077
  - name: "6066"
    port: 6066
    targetPort: 6066
  selector:
    io.kompose.service: spark-unacc-master
status:
  loadBalancer: {}
