apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./spark/unacc/docker-compose.yml.backup
      -o vul_app/spark/unacc/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-unacc-slave
  name: spark-unacc-slave
  namespace: metarget
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: spark-unacc-slave
status:
  loadBalancer: {}
