apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml.backup -o vul_app/home/t-u1804/t-u1804.yaml --volumes hostPath
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: looney-tunables
  name: cve-2023-4911-glibc
  namespace: metarget
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: looney-tunables
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml.backup -o vul_app/home/t-u1804/t-u1804.yaml --volumes hostPath
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/tunables-default: "true"
        io.kompose.service: looney-tunables
    spec:
      containers:
        - image: n7utb/tunables:v6
          name: looney-tunables
          securityContext:
            privileged: true
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
