apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./ntopng/CVE-2021-28073/docker-compose.yml.backup
      -o vul_app/ntopng/CVE-2021-28073/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cve--2021-28073-redis
  name: cve--2021-28073-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve--2021-28073-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./ntopng/CVE-2021-28073/docker-compose.yml.backup
          -o vul_app/ntopng/CVE-2021-28073/ --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: cve--2021-28073-redis
    spec:
      containers:
      - image: redis:6.2-alpine
        imagePullPolicy: ""
        name: cve--2021-28073-redis
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
