apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./solr/CVE-2017-12629-RCE/docker-compose.yml -o RCE-FOR-K8S-4/solr/CVE-2017-12629-RCE/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2017-12629-rce-solr
  name: cve-2017-12629-rce-solr
spec:
  ports:
    - name: "8983"
      port: 8983
      targetPort: 8983
  selector:
    io.kompose.service: cve-2017-12629-rce-solr
status:
  loadBalancer: {}
