apiVersion: v1
kind: Pod
metadata:
  name: mount-host-etc
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: host-etc
      mountPath: /host-etc
  volumes:
    - name: host-etc
      hostPath:
        path: /etc