apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./spring/CVE-2017-8046/docker-compose.yml -o RCE-FOR-K8S-4/spring/CVE-2017-8046/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2017-8046-spring
  name: cve-2017-8046-spring
  namespace: metarget
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2017-8046-spring
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./spring/CVE-2017-8046/docker-compose.yml
          -o RCE-FOR-K8S-4/spring/CVE-2017-8046/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2017-8046-spring
    spec:
      containers:
      - image: vulhub/spring-rest-data:2.6.6
        imagePullPolicy: IfNotPresent
        name: cve-2017-8046-spring
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
