apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./dubbo/CVE-2019-17564/docker-compose.yml.backup
      -o vul_app/dubbo/CVE-2019-17564/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2019-17564-zookeeper
  name: cve-2019-17564-zookeeper
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
  selector:
    io.kompose.service: cve-2019-17564-zookeeper
status:
  loadBalancer: {}
