apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./elasticsearch/CVE-2014-3120/docker-compose.yml -o RCE-FOR-K8S-4/elasticsearch/CVE-2014-3120/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2014-3120-es
  name: cve-2014-3120-es
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
  selector:
    io.kompose.service: cve-2014-3120-es
status:
  loadBalancer: {}
