apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./elasticsearch/CVE-2014-3120/docker-compose.yml -o RCE-FOR-K8S-4/elasticsearch/CVE-2014-3120/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2014-3120-es
  name: cve-2014-3120-es
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2014-3120-es
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./elasticsearch/CVE-2014-3120/docker-compose.yml -o RCE-FOR-K8S-4/elasticsearch/CVE-2014-3120/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2014-3120-es
    spec:
      containers:
        - image: vulhub/elasticsearch:1.1.1
          name: cve-2014-3120-es
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources: {}
      restartPolicy: Always
status: {}
