apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./ofbiz/CVE-2020-9496/docker-compose.yml -o RCE-FOR-K8S-4/ofbiz/CVE-2020-9496/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2020-9496-web
  name: cve-2020-9496-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2020-9496-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./ofbiz/CVE-2020-9496/docker-compose.yml -o RCE-FOR-K8S-4/ofbiz/CVE-2020-9496/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2020-9496-web
    spec:
      containers:
        - image: vulhub/ofbiz:17.12.01
          name: cve-2020-9496-web
          ports:
            - containerPort: 8443
          resources: {}
      restartPolicy: Always
status: {}
