apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./php/CVE-2012-1823/docker-compose.yml -o RCE-FOR-K8S-4/php/CVE-2012-1823/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2012-1823-php
  name: cve-2012-1823-php
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2012-1823-php
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./php/CVE-2012-1823/docker-compose.yml -o
          RCE-FOR-K8S-4/php/CVE-2012-1823/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2012-1823-php
    spec:
      containers:
      - image: vulhub/php:5.4.1-cgi
        imagePullPolicy: IfNotPresent
        name: cve-2012-1823-php
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: cve-2012-1823-php-claim0
      restartPolicy: Always
      volumes:
      - name: cve-2012-1823-php-claim0
        persistentVolumeClaim:
          claimName: cve-2012-1823-php-claim0
status: {}
