apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./samba/CVE-2017-7494/docker-compose.yml -o RCE-FOR-K8S-4/samba/CVE-2017-7494/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2017-7494-samba
  name: cve-2017-7494-samba
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2017-7494-samba
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./samba/CVE-2017-7494/docker-compose.yml -o
          RCE-FOR-K8S-4/samba/CVE-2017-7494/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2017-7494-samba
    spec:
      containers:
      - image: vulhub/samba:4.6.3
        imagePullPolicy: IfNotPresent
        name: cve-2017-7494-samba
        ports:
        - containerPort: 445
        - containerPort: 6699
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /usr/local/samba/etc/smb.conf
          name: cve-2017-7494-samba-claim0
      restartPolicy: Always
      volumes:
      - name: cve-2017-7494-samba-claim0
        persistentVolumeClaim:
          claimName: cve-2017-7494-samba-claim0
status: {}
