name: cve-2019-1002101
class: kubernetes
type: container_escape
dependencies:
  - name: kubectl
    version: 1.11.1
    versions: ~
  - name: kubelet
    version: 1.11.1
    versions: ~
  - name: kubeadm
    version: 1.11.1
    versions: ~

links:
  - https://nvd.nist.gov/vuln/detail/CVE-2019-11246
  - https://github.com/kubernetes/kubernetes/pull/76788
