apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./nexus/CVE-2020-10199/docker-compose.yml -o RCE-FOR-K8S-4/nexus/CVE-2020-10199/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2020-10199-web
  name: cve-2020-10199-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2020-10199-web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./nexus/CVE-2020-10199/docker-compose.yml -o RCE-FOR-K8S-4/nexus/CVE-2020-10199/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2020-10199-web
    spec:
      containers:
        - image: vulhub/nexus:3.21.1
          name: cve-2020-10199-web
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /nexus-data/admin.password
              name: cve-2020-10199-web-claim0
      restartPolicy: Always
      volumes:
        - name: cve-2020-10199-web-claim0
          persistentVolumeClaim:
            claimName: cve-2020-10199-web-claim0
status: {}
