apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./rocketchat/CVE-2021-22911/docker-compose.yml.backup
        -o vul_app/rocketchat/CVE-2021-22911/cve-2021-22911.yaml --volumes hostPath
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: rocketchat
    name: rocketchat
  spec:
    ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    selector:
      io.kompose.service: rocketchat
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./rocketchat/CVE-2021-22911/docker-compose.yml.backup
        -o vul_app/rocketchat/CVE-2021-22911/cve-2021-22911.yaml --volumes hostPath
      kompose.version: 1.21.0 (992df58d8)
      traefik.enable: "false"
    creationTimestamp: null
    labels:
      io.kompose.service: mongo
    name: mongo
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: mongo
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./rocketchat/CVE-2021-22911/docker-compose.yml.backup
            -o vul_app/rocketchat/CVE-2021-22911/cve-2021-22911.yaml --volumes hostPath
          kompose.version: 1.21.0 (992df58d8)
          traefik.enable: "false"
        creationTimestamp: null
        labels:
          io.kompose.service: mongo
      spec:
        containers:
        - args:
          - mongod
          - --smallfiles
          - --oplogSize
          - "128"
          - --replSet
          - rs0
          - --storageEngine=mmapv1
          image: mongo:4.0
          imagePullPolicy: ""
          name: mongo
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./rocketchat/CVE-2021-22911/docker-compose.yml.backup
        -o vul_app/rocketchat/CVE-2021-22911/cve-2021-22911.yaml --volumes hostPath
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: mongo-init-replica
    name: mongo-init-replica
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: mongo-init-replica
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./rocketchat/CVE-2021-22911/docker-compose.yml.backup
            -o vul_app/rocketchat/CVE-2021-22911/cve-2021-22911.yaml --volumes hostPath
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: mongo-init-replica
      spec:
        containers:
        - args:
          - bash
          - -c
          - |-
            for i in `seq 1 30`; do
                mongo mongo/rocketchat --eval "
                  rs.initiate({
                    _id: 'rs0',
                    members: [ { _id: 0, host: 'localhost:27017' } ]})" &&
                s=$? && break || s=$?;
                echo "Tried $i times. Waiting 5 secs...";
                sleep 5;
              done; (exit $s)
          image: mongo:4.0
          imagePullPolicy: ""
          name: mongo-init-replica
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./rocketchat/CVE-2021-22911/docker-compose.yml.backup
        -o vul_app/rocketchat/CVE-2021-22911/cve-2021-22911.yaml --volumes hostPath
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: rocketchat
    name: rocketchat
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: rocketchat
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./rocketchat/CVE-2021-22911/docker-compose.yml.backup
            -o vul_app/rocketchat/CVE-2021-22911/cve-2021-22911.yaml --volumes hostPath
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: rocketchat
      spec:
        containers:
        - args:
          - bash
          - -c
          - |-
            for i in `seq 1 30`; do
                node main.js &&
                s=$? && break || s=$?;
                echo "Tried $i times. Waiting 5 secs...";
                sleep 5;
              done; (exit $s)
          env:
          - name: MAIL_URL
            value: smtp://smtp.email
          - name: MONGO_OPLOG_URL
            value: mongodb://mongo:27017/local
          - name: MONGO_URL
            value: mongodb://mongo:27017/rocketchat
          - name: PORT
            value: "3000"
          - name: ROOT_URL
            value: http://localhost:3000
          image: vulhub/rocketchat:3.12.1
          imagePullPolicy: ""
          name: rocketchat
          ports:
          - containerPort: 3000
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
kind: List
metadata: {}

