apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./ecshop/xianzhi-2017-02-82239600/docker-compose.yml
      -o RCE-FOR-K8S-4/ecshop/xianzhi-2017-02-82239600/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: xianzhi-2017-02-82239600-mysql
  name: xianzhi-2017-02-82239600-mysql
  namespace: metarget
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: xianzhi-2017-02-82239600-mysql
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./ecshop/xianzhi-2017-02-82239600/docker-compose.yml
          -o RCE-FOR-K8S-4/ecshop/xianzhi-2017-02-82239600/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: xianzhi-2017-02-82239600-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: mysql:5.5
        imagePullPolicy: IfNotPresent
        name: xianzhi-2017-02-82239600-mysql
        resources: {}
      restartPolicy: Always
status: {}
