apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./unomi/CVE-2020-13942/docker-compose.yml.backup
      -o vul_app/unomi/CVE-2020-13942/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2020-13942-elasticsearch
  name: cve-2020-13942-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2020-13942-elasticsearch
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./unomi/CVE-2020-13942/docker-compose.yml.backup
          -o vul_app/unomi/CVE-2020-13942/ --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2020-13942-elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: bootstrap.memory_lock
          value: "true"
        - name: cluster.name
          value: contextElasticSearch
        - name: discovery.type
          value: single-node
        image: elasticsearch:7.9.3
        imagePullPolicy: ""
        name: cve-2020-13942-elasticsearch
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
