apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./confluence/CVE-2021-26084/docker-compose.yml.backup
      -o vul_app/confluence/CVE-2021-26084/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2021-26084-web
  name: cve-2021-26084-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2021-26084-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./confluence/CVE-2021-26084/docker-compose.yml.backup
          -o vul_app/confluence/CVE-2021-26084/ --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2021-26084-web
    spec:
      containers:
      - image: vulhub/confluence:7.4.10
        imagePullPolicy: ""
        name: cve-2021-26084-web
        ports:
        - containerPort: 8090
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
