apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./openssl/docker-compose.yaml.backup -o vul_app/openssl/docker-compose-yaml-backup/docker-compose-yaml-backup.yaml --volumes hostPath
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: cve-2022-0778-curl
  name: cve-2022-0778-curl
  namespace: metarget
spec:
  ports:
    - name: "23456"
      port: 23456
      targetPort: 23456
  selector:
    io.kompose.service: cve-2022-0778-curl
