apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./php/fpm/docker-compose.yml.backup
      -o vul_app/php/fpm/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: php-fpm-php
  name: php-fpm-php
  namespace: metarget
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: php-fpm-php
status:
  loadBalancer: {}
