apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2021-43798-web
  name: cve-2021-43798-web
  namespace: metarget
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2021-43798-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2021-43798-web
    spec:
      containers:
        - image: vulhub/grafana:8.2.6
          name: cve-2021-43798-web
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
