apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./coldfusion/CVE-2017-3066/docker-compose.yml.backup
      -o vul_app/coldfusion/CVE-2017-3066/ --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2017-3066-coldfusion
  name: cve-2017-3066-coldfusion
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2017-3066-coldfusion
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./coldfusion/CVE-2017-3066/docker-compose.yml.backup
          -o vul_app/coldfusion/CVE-2017-3066/ --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2017-3066-coldfusion
    spec:
      containers:
      - image: vulhub/coldfusion:11u3
        imagePullPolicy: ""
        name: cve-2017-3066-coldfusion
        ports:
        - containerPort: 8500
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
